image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_SRC_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-src
  CONTAINER_SAMPLES_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-samples
  CONTAINER_PRODUCTION_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  CONTAINER_TEST_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-test
  CONTAINER_DEPLOY_IMAGE: registry.heroku.com/eauc-rt-clj/web

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker pull ${CONTAINER_SRC_IMAGE} || true
    - docker pull ${CONTAINER_SAMPLES_IMAGE} || true
    - docker pull ${CONTAINER_PRODUCTION_IMAGE} || true
    - docker pull ${CONTAINER_TEST_IMAGE} || true
    - docker build --cache-from ${CONTAINER_SRC_IMAGE} -t ${CONTAINER_SRC_IMAGE} --target src .
    - docker build --cache-from ${CONTAINER_SRC_IMAGE} --cache-from ${CONTAINER_SAMPLES_IMAGE} -t ${CONTAINER_SAMPLES_IMAGE} --target samples .
    - docker build --cache-from ${CONTAINER_SRC_IMAGE} --cache-from ${CONTAINER_SAMPLES_IMAGE} --cache-from ${CONTAINER_PRODUCTION_IMAGE} -t ${CONTAINER_PRODUCTION_IMAGE} --target production .
    - docker build --cache-from ${CONTAINER_SRC_IMAGE} --cache-from ${CONTAINER_SAMPLES_IMAGE} --cache-from ${CONTAINER_PRODUCTION_IMAGE} --cache-from ${CONTAINER_TEST_IMAGE} -t ${CONTAINER_TEST_IMAGE} --target test .
    - docker push $CONTAINER_SRC_IMAGE
    - docker push $CONTAINER_SAMPLES_IMAGE
    - docker push $CONTAINER_PRODUCTION_IMAGE
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  script:
    - docker pull ${CONTAINER_TEST_IMAGE}
    - docker run --rm $CONTAINER_TEST_IMAGE

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker pull ${CONTAINER_PRODUCTION_IMAGE}
    - docker tag ${CONTAINER_PRODUCTION_IMAGE} ${CONTAINER_DEPLOY_IMAGE}
    - docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com
    - docker push ${CONTAINER_DEPLOY_IMAGE}
    - docker run --rm -e HEROKU_API_KEY=${HEROKU_API_KEY} wingrunr21/alpine-heroku-cli container:release web --app eauc-rt-clj
